<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => '任务管理',
                'parent_id' => 0,
                'icon' => 'dashboard',
                'url' => '',
                'description' => '任务管理',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 2,
                'name' => '任务管理',
                'parent_id' => 1,
                'icon' => '',
                'url' => 'task_manage',
                'description' => '任务管理',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 3,
                'name' => '创建任务',
                'parent_id' => 1,
                'icon' => '',
                'url' => 'add_task',
                'description' => '创建任务',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 4,
                'name' => '用户管理',
                'parent_id' => 0,
                'icon' => 'account_box',
                'url' => '',
                'description' => '用户管理',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 5,
                'name' => '用户列表',
                'parent_id' => 4,
                'icon' => '',
                'url' => 'user_lists',
                'description' => '用户列表',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 6,
                'name' => '创建用户',
                'parent_id' => 4,
                'icon' => '',
                'url' => 'add_user',
                'description' => '创建用户',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 7,
                'name' => '更新用户',
                'parent_id' => 4,
                'icon' => '',
                'url' => 'user_update',
                'description' => '更新用户',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 8,
                'name' => '工作通知',
                'parent_id' => 0,
                'icon' => 'message',
                'url' => '',
                'description' => '工作通知',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 9,
                'name' => '任务通知',
                'parent_id' => 8,
                'icon' => '',
                'url' => 'notify',
                'description' => '任务通知',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 10,
                'name' => '预置数据',
                'parent_id' => 0,
                'icon' => 'multiline_chart',
                'url' => '',
                'description' => '预置数据',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 11,
                'name' => '学院名称设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'colleges',
                'description' => '学院名称设置',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 12,
                'name' => '工作类型设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'work_type',
                'description' => '工作类型设置',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 13,
                'name' => '对口科室设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'department',
                'description' => '对口科室设置',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 14,
                'name' => '考核等级设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'access',
                'description' => '考核等级设置',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 15,
                'name' => '任务列表',
                'parent_id' => 1,
                'icon' => '',
                'url' => 'tasks_of_college',
                'description' => '学院显示的任务列表',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 16,
                'name' => '任务列表',
                'parent_id' => 1,
                'icon' => '',
                'url' => 'tasks_of_teacher',
                'description' => '老师显示的任务列表',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 17,
                'name' => '会议管理',
                'parent_id' => 0,
                'icon' => 'card_membership',
                'url' => '',
                'description' => '会议管理',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 18,
                'name' => '会议记录',
                'parent_id' => 17,
                'icon' => '',
                'url' => 'cahier_lists',
                'description' => '会议记录',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 19,
                'name' => '创建会议',
                'parent_id' => 17,
                'icon' => '',
                'url' => 'cahier_create',
                'description' => '创建会议',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 20,
                'name' => '任务汇总',
                'parent_id' => 0,
                'icon' => 'bubble_chart',
                'url' => '',
                'description' => '任务汇总',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 21,
                'name' => '任务汇总',
                'parent_id' => 20,
                'icon' => '',
                'url' => 'task_summary',
                'description' => '任务汇总',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 22,
                'name' => '图表显示',
                'parent_id' => 20,
                'icon' => '',
                'url' => 'echart',
                'description' => '图表显示',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 23,
                'name' => '缺勤原因设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'absence',
                'description' => '缺勤原因',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'id' => 24,
                'name' => '学期学年设置',
                'parent_id' => 10,
                'icon' => '',
                'url' => 'semester',
                'description' => '学期学年设置',
                'is_nav' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
