<?php

namespace App\Models;

use App\Models\Traits\Listable;
use Illuminate\Auth\Access\Gate;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends BaseModel implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, Notifiable, Listable;
    use EntrustUserTrait {
        EntrustUserTrait::can as may;
        Authorizable::can insteadof EntrustUserTrait;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'nickname', 'phone', 'gender', 'college_id', 'department_id', 'picture'
    ];

    protected static $allowSearchFields = ['name', 'gender', 'role_id', 'nickname', 'college_id'];
    protected static $allowSortFields = ['name', 'nickname', 'gender', 'college_id', 'department_id'];

    protected $casts = [
        'gender' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];


    public function isSuperAdmin()
    {
        return $this->hasRole('super_admin');
    }

    /*public function scopeFromRoles($query, array $role)
    {
        return $query->hasRole($role);
    }*/

    /**
     * 用户角色
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function authorize($ability, $arguments = [])
    {
        return app(Gate::class)->forUser($this)->authorize($ability, $arguments);
    }

    public function getKey()
    {
        return parent::getKey(); // TODO: Change the autogenerated stub
    }

    public function college()
    {
        return $this->hasOne(College::class, 'id', 'college_id');
    }
}

