<?php

namespace App\Models;

use Illuminate\Auth\Access\Gate;
use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends BaseModel implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, Notifiable;
    use EntrustUserTrait {
        EntrustUserTrait::can as may;
        Authorizable::can insteadof EntrustUserTrait;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'gender', 'college_id', 'department_id', 'picture'
    ];

    protected $casts = [
        'gender' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];


    // todo 这里的修改器不能正常修改性别，不知道为什么，但是修改其他的字段都可以
    /*public function getGenderAttribute($value)
    {
        return $this->attributes['gender'] = $value?'男':'女';
    }*/

    public function isSuperAdmin()
    {
        return $this->hasRole('super_admin');
    }

    /**
     * 用户角色
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function authorize($ability, $arguments = [])
    {
        return app(Gate::class)->forUser($this)->authorize($ability, $arguments);
    }

    public function getKey()
    {
        return parent::getKey(); // TODO: Change the autogenerated stub
    }

}

